resibots/limbo

- boost.py
- mkl.py
- openmp.py
- wscript
Added mkl.py for declaration and detection of MKL.
Added openmp.py for declaration and detection of compiler OpenMP support (original code took from waf-extras repository, modified it a little).
Small modification on boost.py to support Intel Compiler (didn't worked before that).
Addition of the mkl and openmp python files to limbo wscript. Also Sublime automatically fixed styling warnings, mostly spacings and indentations (all was really bad indented when looking at it on Sublime, but maybe on OS X it looked good, so I can undo this change).
> Support for Intel Compiler and Math Kernel Library

- limbo.py
I am correcting a typo in `limbo.py` for the OAR functionality. The `nodes` should be first!
> Small correction in OAR limbo argument

- src/limbo/rprop.hpp
The params that were saved were not the best ones; instead, they were the modified ones (the next ones). This would be incorrect when the modification does not help.
> Corrected a bug in the rprop

- src/limbo/init/random_sampling.hpp
- src/limbo/model/gp.hpp
Very minor fix required for clang. I suppose this is because of yesterday's patch by Federico.
> Fixed missing includes of the standard library (vector & iostream)

- src/limbo/bayes_opt/bo_base.hpp
- src/limbo/bayes_opt/boptimizer.hpp
- src/limbo/stat.hpp
- src/limbo/stat/console_summary.hpp
As discussed in #53, it's better to have the standard output in stats. I created a stat `ConsoleSummary` that directly outputs in the standard output (std::cout) only if the user wants it (e.g. debugging purposes). It is enabled in the defaults: I am assuming that new users (that will use the defaults) should get some standard output.
> Move standard output to stats

- src/cmaes/cmaes.c
- src/ehvi/ehvi_calculations.cc
- src/ehvi/ehvi_multi.cc
- src/ehvi/ehvi_sliceupdate.cc
- src/limbo/bayes_opt/boptimizer.hpp
- src/limbo/init/random_sampling.hpp
- src/limbo/model/gp.hpp
- src/limbo/opt/cmaes.hpp
- src/limbo/opt/grid_search.hpp
- src/limbo/opt/parallel_repeater.hpp
- src/limbo/opt/rprop.hpp
- src/limbo/stat/stat_base.hpp
- src/limbo/tools.hpp
- src/limbo/tools/math.hpp
- src/limbo/tools/sys.hpp
- src/tests/test_gp.cpp
There is no reason to use boost's shared_ptr since they have been included in the standard.
> removed boost::shared_ptr and replaced them with std::shared_ptr

- src/limbo/bayes_opt.hpp
- src/limbo/bayes_opt/bo_base.hpp
- src/limbo/opt.hpp
- src/tests/wscript
- Conditionally including NLOpt and CMAES headers in the opt.hpp header and in bo_base
- Conditionally including the multi objective optimizers in bayes_opt.hpp if USE_SFERES is defined
- Fixed typo in the declaration of the default acqui optimizer when using NLOPT. Also fixed the algorithm constant
- Removed unnecesary dependencies in the tests wscript
> Conditional includes and minor bug fix

- src/limbo/bayes_opt/bo_base.hpp
- src/limbo/bayes_opt/boptimizer.hpp
- src/tests/boptimizer.cpp
It is not a good idea to catch *everything* from the optimised function. I propose to define an EvaluationError exception.
> Exception name

- src/limbo/bayes_opt/bo_base.hpp
- src/limbo/tools/math.hpp
This pull request solves #73 and throws an `EvaluationError` exception when we have a inf or NAN value in `bo_base::add_new_sample`.
> Fix for helper math func + exception at inf/nan

- waf_tools/limbo.py
Small fix for C++ flags propagation. We weren't propagating the C++ flags to the limbo variants.
> Small fix for C++ flags propagation

- waf_tools/limbo.py
Small improvement: **Multiple configs in json for OAR/Torque**.
Now we can do this:
```json
[{
"exps" : ["test_exp_name"],
"bin_dir" : "/home/test_binary_dir",
"res_dir" : "/home/test_result_dir",
"args" : "argument1 argument2",
"email" : "myname@email.com",
"wall_time" : "00:03:00",
"nb_runs" : 100,
"nb_cores" : 2
},
{
"exps" : ["test_exp_name"],
"bin_dir" : "/home/test_binary_dir",
"res_dir" : "/home/different_test_result_dir",
"args" : "different_argument1 differet_argument2",
"email" : "myname@email.com",
"wall_time" : "00:03:00",
"nb_runs" : 100,
"nb_cores" : 2
}]
```
Where as before we would need 2 different json files. We can still have only 1 config like this:
```json
[{
"exps" : ["test_exp_name"],
"bin_dir" : "/home/test_binary_dir",
"res_dir" : "/home/test_result_dir",
"args" : …
```
> Multiple configs in json for OAR/Torque

- src/limbo/bayes_opt/boptimizer.hpp
No need to check for samples size in boptimizer loop.. This is probably left from older versions. Now everything is checked (and should be) in the stop criteria.
> BOptimizer stop check fix

- waf_tools/limbo.py
Allow multiple source files in variants. First file is the file that the variant target take the name from. For example now you can do this:
```python
limbo.create_variants(bld,
source = 'hexa_repertoire.cpp test.cpp',
uselib_local = 'limbo',
uselib = libs,
includes=". ../../src ../ ",
cxxflags = cxxflags,
variants = ['SIMU'])
```
The target created would be `hexa_repertoire_simu`.
> Allow multiple source files in variants

- src/limbo/bayes_opt/boptimizer.hpp
- src/limbo/model/gp.hpp
- src/tests/test_gp.cpp
#84 produced a bug when calling the BOptimizer. So, I re-enabled the dimensions in GP's constructor and altered BOptimizer to properly handle the cases.
The test "boptimizer" was failing with assertions. I, also, created a new gp test for this specific case.
Thanks @vassilisvas for pointing the bug out.
> Fix for gp nodim bug

- src/limbo/tools/parallel.hpp
Useful for traversing containers with not standard iterators (e.g. std::maps).
Usage:
```cpp
auto body = [&](Item it) {
// Loop iteration
};
tools::par::for_each(container.begin(), container.end(), body);
```
> Added parallel foreach

- src/limbo/opt.hpp
- src/limbo/opt/chained.hpp
- src/tests/test_optimizers.cpp
Hi guys! 
I implemented the `Chained` optimizer, something I think I might have discussed with some of you when speaking of BayesOpt.
I did it using variadic templates (instead of using maybe Boost's Fusion Vectors) because it is super easy and straightforward. 
I also added a test, and checked that things are called in the right order(using the awesome `typeid(T).name()` feature).
Here I show you an approximate example of doing what BayesOpt does:
```
struct ParamsDIRECT {
struct opt_nloptnograd {
BO_PARAM(int, iterations, (500 * F_DIM * 0.9)); // This may give compiler error, you can change it if you want
};
};
struct ParamsBOBYQA {
struct opt_nloptnograd {
BO_PARAM(int, iterations, (500 * F_DIM * 0.1)); // Same here
};
};
struct Params {
....
};
...
typedef opt::Chained<Params, …
```
> Chained Optimizer

- src/examples/experimental/imgpo.cpp
- src/examples/experimental/parego.cpp
- src/examples/mono_dim.cpp
- src/examples/obs_multi.cpp
- src/examples/obs_multi_auto_mean.cpp
- src/limbo/kernel/exp.hpp
- src/limbo/kernel/matern_five_halfs.hpp
- src/limbo/kernel/matern_three_halfs.hpp
- src/limbo/kernel/squared_exp_ard.hpp
- src/limbo/model/gp.hpp
- src/tests/all_combinations_template.cpp
- src/tests/test_gp.cpp
- src/tests/test_kernel.cpp
After inside conversations that we had, we said to try implementing this for initializing/scaling the variance. In a glance:
- Every kernel has the following parameters (if applicable):
- `sigma_sq`: signal variance (sigma squared) - this applies to all kernels
- `l`: characteristic length scale - this is not applicable to `SquaredExpARD`
- Fixed issue in GP: we were outputting `sigma^2` if the GP already had samples and `sigma` if not.
I believe this is cleaner and we are able to properly (and easily) set the initial/max variance. It changes a little bit the API, but we still haven't fixed it. What do you think?
> Fix for gp var + kernel parameters

- src/limbo/model/gp/no_lf_opt.hpp
Assertion for calling HyperParams Opt without opt as discussed in #120
> Assertion for calling HyperParams Opt without opt

- src/limbo/kernel/squared_exp_ard.hpp
- src/tests/test_gp.cpp
- src/tests/test_kernel.cpp
If the CI passes, ready to be merged.
(and the benchmarks to be relaunched)
> Remove the optimization of the unused HP in SE_ARD

- src/benchmarks/bayesopt/hp_opt.cpp
- src/benchmarks/bayesopt/simple.cpp
- src/benchmarks/bayesopt/testfunctions.hpp
- src/benchmarks/limbo/hp_opt.cpp
- src/benchmarks/limbo/simple.cpp
- src/benchmarks/limbo/testfunctions.hpp
- src/examples/mono_dim.cpp
- src/examples/obs_multi.cpp
- src/limbo/bayes_opt/bo_base.hpp
- src/limbo/kernel/matern_five_halfs.hpp
- src/limbo/kernel/matern_three_halfs.hpp
- src/tests/create_all_combinations_test.py
- src/tests/test_gp.cpp
Hi, 
As pointed out by JBM, there were some typos in the names of the function used in the benchmark. 
This PR removes theses typos (or at least those that I saw).
> fix typos in names of the benchmark function

- waf_tools/limbo.py
- waf_tools/params.py
- wscript
- now the actual parameters of an experiments are written in the experiment file
- ./waf --write_params=filename will write the limbo default params in a markdown file called 'filename'
- copy the parameters when submitting an experiment to a cluster (e.g. --oar), so that we can know what we have run
> finish the waf script for printing default params

- docs/faq.rst
- src/limbo/model/gp/hp_opt.hpp
We should remove the assertion because if we use the `BOptimizer` class and the GP with learning the hyperparameters and no initialization function, then it gets triggered. This happens because the compiler calls the descructor of the GP at this [line](https://github.com/resibots/limbo/blob/42d9ccac68017edcdff289179474db7c9d62c4c3/src/limbo/bayes_opt/boptimizer.hpp#L147).
> HP Opt remove assertion

- docs/api.rst
- src/examples/obs_multi_auto_mean.cpp
- src/limbo/acqui/ei.hpp
- src/limbo/acqui/gp_ucb.hpp
- src/limbo/acqui/ucb.hpp
- src/limbo/bayes_opt/boptimizer.hpp
- src/limbo/stat/gp.hpp
- src/limbo/stat/gp_acquisitions.hpp
- src/tests/test_gp.cpp
Enable acquisition function optimization with gradients. Minor changes in the API:
- The acquisition functions should return the `opt::eval_t` type and not `double`
- The acquisition functions expect one more parameter: a boolean value whether they should return the gradient or not.
I am preparing a small example (I will also maybe add it in the docs) for showcase.
Let me know what you think...
> Enable acquisition function optimization with gradients

- src/examples/experimental/cbo.cpp
- src/examples/experimental/wscript
- src/limbo/experimental/acqui/eci.hpp
Expected Constrained Improvement (instead of Constrained Expected improvement) reflects better what we do and is consistent with the theory we follow, therefore renaming acronyms from CEI to ECI
> Naming conventions for constrained BO

- src/limbo/bayes_opt/boptimizer.hpp
- src/limbo/tools/random_generator.hpp
- src/tests/test_boptimizer.cpp
- src/tests/test_gp.cpp
Since we may want to use Bayesian Optimization to optimize an unbounded function, I added one option to do that. Note that optimizing an acquisition function (especially Expected Improvement) becomes a much more difficult problem if it is unbounded, so by default we still optimize bounded functions (in **[0-1]**). I added a test for unbounded optimization and I had to do a small change in the `random_vector` implementation (no API change though).
Let me know what you think!
> Option for unbounded BO

- src/limbo/model/gp.hpp
Hi all,
A small change that prevent the GP to reconstruct the Mean Object as long as there is not difference in dim_out. 
While it's a minor performance improvement, it also allows to have more advance mean object that can store data over the time.
If the CI passes, it's ready to merge.
> Avoiding to reconstruct the mean object when it's not necessary.

- src/limbo/model/gp.hpp
- src/limbo/model/gp/mean_lf_opt.hpp
Hi all, 
I realized that the Mean_lf_opt object actually recomputes the kernel at each iteration of the HP optimization, while it's useless (this object is supposed to only change the HP associated to the mean). I removed all the unnecessary computation and I needed a new public method to recompute "_obs_mean" and "_alpha" (feel free to change the name if you do not like it).
> avoid to recompute the kernel when not needed in MeanLF

- docs/tutorials/quick_start.rst
- waf_tools/exp_template.cpp
- waf_tools/limbo.py
Hi, 
I simply copied the line about cloning Limbo in the Compiling section.
Moreover, I change the parameter in --create exp, because it seemed that the default value of BAYES_OPT_BOBASE_STATS_ENABLED did not work (I changed it into BAYES_OPT_BOBASE_STATS_DISABLED.
Let me know what do you think.
> Fix quickstart

- docs/tutorials/gp.rst
- src/limbo/bayes_opt/boptimizer.hpp
One of my colleague using limbo spotted a few typos in the api documentation, and found that the complete source code at the end of the GP tutorial was missing. 
I fixed this.
> Fix minor typos

- src/limbo/opt/cmaes.hpp
- src/tutorials/advanced_example.cpp
Adds parameters to the CMA-ES wrapper. Using the default options leaves the previous parameters as they were used before.
Quick remark to take into account: It seems different variants of CMA-ES are using the parameters differently. For example, in the case of aIPOP_CMAES, the maximum function evaluation is global across restarts, while in aBIPOP_CMAES is local in a restart. This normally will give us a greater number of evaluations when using aBIPOP.
Some quick reference about the new parameters:
- variant: Allows to change the variant to be used during the optimization. Possible values are: CMAES_DEFAULT, IPOP_CMAES, BIPOP_CMAES, aCMAES, aIPOP_CMAES, aBIPOP_CMAES, sepCMAES, sepIPOP_CMAES, sepBIPOP_CMAES, sepaCMAES, sepaIPOP_CMAES, sepaBIPOP_CMAES, VD_CMAES, VD_IPOP_CMAES and …
> Additional parameters for CMAES

- src/limbo/opt/cmaes.hpp
I think we should scale the sigma in CMA-ES when the bounds are not in `[0,1]`..
> Scale sigma in CMA-ES

- wscript
We forgot to correct the bug for the intel compiler also. See #200 ...
> Removed forgotten flag for libcmaes

- src/benchmarks/limbo/bench.cpp
- src/limbo/opt/cmaes.hpp
A few more parameters for CMA-ES that are needed for Black-DROPS:
- **lambda** (int): control the initial population, automatically determined if -1
- **stochastic** (bool): if this is on, the mean of the last distribution is returned; otherwise, the best ever candidate is returned. If *handle_uncertainty* is on, this is also enabled.
> Adds 2 more parameters to CMA-ES

- wscript
This solves #267.. If the compiler does not support C++14, it disables it (with a warning) even if requested..
> C++14 flag as requested per #267

- src/limbo/tools/random_generator.hpp
I had a need for changing seeds, params and resetting the random generator (and/or the underlying distribution). I provide a small fix that does not change the API at all, but gives more flexibility to someone that wants it. Btw, we could discuss a way of providing it throughout limbo; i.e., in our optimizers, initiliazers etc. I will open an issue about this..
> Provide more configurable random generator

- src/limbo/opt/cmaes.hpp
In bounded CMA-ES the initial point was not transformed back to the genotype and thus was not handled properly if it was not random.. This PR fixes this issue..
> Minor fix for bounded CMA-ES

- .travis.yml
- ci/install_libcmaes.sh
- src/limbo/opt/cmaes.hpp
- wscript
This PR attempts to solve #306 to expose all (or most of) libcmaes stopping criteria parameters. It also fixes a small bug in setting one of them.
> Expose all (or most of) libcmaes stopping criteria parameters

- src/limbo/tools/sys.hpp
Hi,
When I tried building a program using Limbo with MinGW (a Windows port of GCC), I got the following error.
```
C:/Users/chris/Programming/C++/Correrender/third_party/limbo/src/limbo/tools/sys.hpp:72:23: error: gethostname' was not declared in this scope; did you mean 'hostname'?
72 |             int res = gethostname(hostname, 50);
|                       ^~~~~~~~~~~
|                       hostname
```
This PR adds an include to winsock2.h when using MinGW, which seems to contain the function declaration of `gethostname` for MinGW. I can confirm that the build then runs without any further compiler errors.
> Add missing include for build with MinGW

- CMakeLists.txt
- cmake/limboConfig.cmake.in
- package.xml
- src/limbo/kernel/kernel.hpp
- src/limbo/mean/mean.hpp
This includes Cmake configuration files and `package.xml` to build limbo using catkin. This builds upon the CmakeLists file configured by @buschbapti on his fork. Hopefully this makes it easier for other ROS users.
> Enable catkin compatibility
