resibots/limbo

src/limbo/bo_base.hpp, src/limbo/boptimizer.hpp, src/limbo/ehvi.hpp, src/limbo/gp.hpp, src/limbo/gp_auto.hpp, src/limbo/gp_auto_mean.hpp, src/limbo/nsbo.hpp, src/limbo/parego.hpp, src/limbo/stat.hpp, src/tests/test_gp.cpp
Integrated blacklist functionality into GP and added a unit test to ensure that it behaves as expected.
Also added the utilization of blacklists in the simple bayesian optimizer.
Maybe they can be added to the multi objective optimization too.  @jbmouret opinion on that?
=> Gp multi blacklist

src/limbo/gp_auto.hpp, src/limbo/gp_auto_mean.hpp
Added the improvement in the likelihood computation @jbmouret talked about in #9 .
=> Improvement in likelihood computation

tools/clean_code.py
=> Correct the check on number of arguments (clang-format)

src/limbo/macros.hpp, src/tests/test_macros.cpp, src/tests/wscript
I have used this feature for my experiments, and I think it's okay to add it to the codebase
=> Added PARAM_ARRAY and STRING macros (copied from sferes)

src/examples/obs_multi_auto_mean.cpp, src/limbo/bayes_opt/bo_base.hpp, src/limbo/bayes_opt/bo_multi.hpp, src/limbo/bayes_opt/boptimizer.hpp, src/limbo/bayes_opt/ehvi.hpp, src/limbo/bayes_opt/nsbo.hpp, src/limbo/bayes_opt/parego.hpp, src/limbo/init/random_sampling.hpp, src/limbo/mean/constant.hpp, src/limbo/mean/data.hpp, src/limbo/mean/function_ard.hpp, src/limbo/mean/null_function.hpp, src/limbo/model/gp.hpp, src/limbo/model/gp_auto.hpp, src/limbo/model/gp_auto_mean.hpp
=> Removed ObsType

src/limbo/bayes_opt/bo_base.hpp, src/limbo/bayes_opt/boptimizer.hpp, src/limbo/bayes_opt/ehvi.hpp, src/limbo/bayes_opt/nsbo.hpp, src/limbo/bayes_opt/parego.hpp, src/limbo/stop/chain_criteria.hpp, src/limbo/stop/max_iterations.hpp, src/limbo/stop/max_predicted_value.hpp
- Changed Stopping Criteria structs to return true when the BO has to be stopped
- Changed the name of the method _pursue to _stop
=> Fixed Stopping Criteria behaviour

src/examples/obs_multi_auto_mean.cpp, src/limbo/model/gp/kernel_lf_opt.hpp, src/limbo/model/gp/kernel_mean_lf_opt.hpp, src/limbo/model/gp/mean_lf_opt.hpp
Just that, and a little fix in the obs_multi example
=> Ability to select which optimizer to use for GP likelihood optimization

src/tests/boptimizer.cpp, src/tests/wscript
It seems that letting it run for longer solved the issue. But it takes much more time so I removed it from the tests. Please run it many times and tell me if it fails.
=> Test boptimizer fix

src/examples/wscript, src/tests/wscript
=> Fixes for annoying warnings

waf_tools/limbo.py
Small fix for variant creation/compilation. This fix does not create new files. Just produces the targets.
=> Fix for variants..Do not create new files

src/limbo/bayes_opt/bo_base.hpp, src/limbo/bayes_opt/boptimizer.hpp, src/limbo/init/grid_sampling.hpp, src/limbo/init/random_sampling.hpp, src/limbo/init/random_sampling_grid.hpp
Added new function in bo_base that evaluates a sample, catches exception, and adds to samples or bl_samples acordingly
=> Initialization Blacklisting

src/tests/bo_functions.cpp
This fixes #89 ! **Merging** at once..
=> bo_functions no TBB fix

.travis.yml, README.md, ci/install_libcmaes.sh, ci/install_nlopt.sh, ci/install_tbb.sh, ci/run_extensive.sh, src/tests/test_cmaes.cpp, src/tests/test_gp.cpp, src/tests/test_init_functions.cpp, src/tests/test_macros.cpp, src/tests/test_nlopt.cpp, src/tests/test_optimizers.cpp, src/wscript, waf_tools/limbo.py, wscript
This PR aims to fix travis.. It is **not to be merged** yet..
=> Fix travis

src/examples/mono_dim.cpp, src/examples/obs_multi.cpp, src/examples/obs_multi_auto_mean.cpp, src/limbo/bayes_opt/boptimizer.hpp, src/limbo/experimental/bayes_opt/imgpo.hpp, src/limbo/model/gp.hpp, src/tests/all_combinations_template.cpp, src/tests/bo_functions.cpp, src/tests/boptimizer.cpp, src/tests/test_init_functions.cpp
- explicitly call the HP optimization
- add a parameter in bayesian_optimizer to control the frequency of the HP optimization (hp_period)
=> Explicit call to the hyper parameter optimizers

docs/tutorials/basic_example.rst, src/examples/experimental/imgpo.cpp, src/examples/mono_dim.cpp, src/limbo/experimental/model/gp_parego.hpp, src/limbo/tools/math.hpp, src/limbo/tools/random_generator.hpp, src/tests/bo_functions.cpp, src/tests/test_gp.cpp, src/tests/test_init_functions.cpp, src/tests/test_optimizers.cpp
Just add a simple tools::make_vector() to make it easier to return a single value when we expect a vector (typically, for the functions that are optimized).
=> Small tools

src/limbo/tools/rand_utils.hpp, src/limbo/tools/random_generator.hpp
As mentioned by @fedeallocati, this alternative for random seeding seems like a good addition.
=> Fix for #113

src/limbo/bayes_opt/bo_base.hpp, src/limbo/bayes_opt/boptimizer.hpp, src/tests/boptimizer.cpp, src/tests/test_boptimizer.cpp, src/tests/wscript
Fix for #81 .. It is a little hacky, but it will save us from many unforeseen traps.. I also enabled the `boptimizer` test in the test routines...
=> Fix for boptimizer inheritance bug

docs/tutorials/gp.rst, docs/tutorials/statistics.rst
Please review quickly these re-phrasings to be included in the Gaussian Process tutorial.
=> A few rephrasings

src/hv/hypervol.c, src/hv/hypervol.h, src/limbo/experimental/bayes_opt/bo_multi.hpp, src/limbo/experimental/bayes_opt/parego.hpp, src/limbo/experimental/stat/pareto_front.hpp, src/limbo/experimental/tools/pareto.hpp, src/limbo/opt.hpp, src/limbo/stop.hpp, src/limbo/stop/max_iterations.hpp, src/limbo/tools/math.hpp, src/tutorials/gp.cpp
Ran clang-format on whole repo as discussed in #142 .
I will **merge** as soon as the tests pass..
=> Ran clang-format on whole repo

src/examples/experimental/parego.cpp, src/examples/mono_dim.cpp, src/examples/obs_multi.cpp, src/examples/obs_multi_auto_mean.cpp, src/limbo/kernel.hpp, src/limbo/kernel/exp.hpp, src/limbo/kernel/matern_five_halves.hpp, src/limbo/kernel/matern_three_halves.hpp, src/limbo/kernel/squared_exp_ard.hpp, src/tests/all_combinations_template.cpp, src/tests/test_gp.cpp, src/tests/test_init_functions.cpp
Continuation of #148 for Matern Kernels...
=> Fix typos in matern kernels

docs/api.rst, docs/faq.rst, src/limbo/model/gp.hpp, src/limbo/model/gp/hp_opt.hpp, src/limbo/model/gp/kernel_lf_opt.hpp, src/limbo/model/gp/kernel_mean_lf_opt.hpp, src/limbo/model/gp/mean_lf_opt.hpp, waf_tools/limbo.py, waf_tools/params.py, wscript
As discussed in #151, I added a question in the FAQ. Probably it needs some rephrasing..
=> Fix for #151

docs/tutorials/advanced_example.rst, docs/tutorials/basic_example.rst, docs/tutorials/external_libs.rst, docs/tutorials/gp.rst, docs/tutorials/opt.rst, docs/tutorials/statistics.rst
Documentation fix as remarked in #160..
=> Fix for #160

src/limbo/acqui/ei.hpp, src/limbo/model/gp.hpp, src/tests/test_boptimizer.cpp, src/tutorials/advanced_example.cpp
I think we should have EI in our library and it would be good for the paper too. I need to work a little more on it.
=> Expected Improvement

src/examples/experimental/multi.cpp, src/examples/experimental/parego.cpp, src/examples/mono_dim.cpp, src/examples/obs_multi.cpp, src/examples/obs_multi_auto_mean.cpp, src/limbo/bayes_opt/boptimizer.hpp, src/limbo/experimental/bayes_opt/ehvi.hpp, src/tests/bo_functions.cpp, src/tests/test_boptimizer.cpp, src/tests/test_init_functions.cpp, src/tests/wscript, src/tutorials/basic_example.cpp, src/tutorials/statistics.cpp
Setting NLOpt DIRECT as default acquisition function optimizer as discussed in #146....
=> NLOpt DIRECT as default

README.md
- Done to match http://www.resibots.eu/limbo/
=> Renaming *optimisation* to **optimization**

src/examples/experimental/constrained_ei.cpp, src/examples/experimental/wscript, src/limbo/experimental/acqui/cei.hpp, src/limbo/experimental/bayes_opt/cboptimizer.hpp
**Work in progress**
Initial attempt on bo with constraints
=> Bo with constraints

src/examples/experimental/multi.cpp, src/examples/experimental/wscript, src/limbo/experimental/bayes_opt/ehvi.hpp, src/limbo/experimental/bayes_opt/nsbo.hpp
***Work in progress***
- Cleaning up a few things in the code
- Updating the multi.cpp example to produce variants/executables for all MO algorithms
Todo:
- Make NSBO run correctly
=> Cleaning experimental/Multi objective

src/limbo/opt/nlopt_grad.hpp, src/limbo/opt/nlopt_no_grad.hpp
Fix for NLOpt failure exception
=> Fix for NLOpt failure

src/limbo/acqui/ei.hpp, src/limbo/experimental/acqui/eci.hpp, src/limbo/experimental/bayes_opt/cboptimizer.hpp
Expected Improvement computation time improvement. Now it executes much much faster than before (almost as fast as UCB --- it cannot be as fast).
If you have any other ideas to make it better please let me know.
=> Expected Improvement computation time improvement

src/examples/experimental/cbo.cpp, src/limbo/experimental/acqui/eci.hpp, src/limbo/experimental/bayes_opt/cboptimizer.hpp
=> Experimental fixes

src/benchmarks/limbo/hp_opt.cpp, src/benchmarks/limbo/simple.cpp, src/benchmarks/wscript
Keep benchmarks up to date with changes in limbo...
=> Fixes for benchmarks to compile

docs/tutorials/advanced_example.rst, docs/tutorials/basic_example.rst, docs/tutorials/compilation.rst, docs/tutorials/gp.rst, docs/tutorials/quick_start.rst, wscript
=> Improving documentation

waf_tools/tbb.py
=> Fix for tbb detection

docs/tutorials/basic_example.rst, docs/tutorials/gp.rst, docs/tutorials/opt.rst, docs/tutorials/statistics.rst
Minor tutorial fixes after the license updates.
=> Minor tutorial fixes

docs/tutorials/basic_example.rst, src/limbo/opt/cmaes.hpp, src/limbo/tools/random_generator.hpp
Minor fix in cmaes wrapper.. We were resetting to fixed values the initial point..
=> Fix for cmaes

wscript
=> Removes compiler flag for libcmaes problems

src/limbo/opt/cmaes.hpp
Small addition since it seems that libcmaes handles bounds with special care..
=> Give possibility to alter bounds in libcmaes

src/limbo/experimental/model/spgp.hpp
Introduces the sparse gaussian process model as an alternative to be used. The implementation is based in the original matlab code by Edward Snelson (2006).
=> Sparse GPs

docs/tutorials/compilation.rst
=> Handle issue #212

src/limbo/kernel/kernel.hpp, src/limbo/model/gp.hpp, src/limbo/model/gp/kernel_lf_opt.hpp, src/limbo/model/gp/kernel_mean_lf_opt.hpp, src/tests/test_boptimizer.cpp, src/tests/test_gp.cpp, src/tutorials/plot_gp.py
As discussed in #209, this pull-request fixes the issues introduced with kernel restructuring (#209).. In addition, I made minor improvements in the unit tests for the GP...
@Aneoshun @jbmouret Let me know if it works and if you have any issues/objections...
=> Fix issues with kernel restructuring

src/limbo/opt/parallel_repeater.hpp, src/tests/test_optimizers.cpp
Fixes the bug in parallel repeater - see #218. I added some unit tests and an additional parameter to the `parallel_repeater` class to handle how big deviation around the initial point we would like to have.
=> Fix for bug in parallel repeater - see #218

src/limbo/opt/rprop.hpp, src/tests/test_optimizers.cpp
=> Fix for #213

docs/guides/bo.rst, src/limbo/kernel/exp.hpp
Fixing some errors in the docs (see #226)..
Thanks to @alexendy...
=> Fixes in docs

waf_tools/eigen.py, waf_tools/libcmaes.py, waf_tools/nlopt.py, waf_tools/tbb.py, wscript
Hi all, 
I quickly changed the scripts used to find eigen and tbb so that they can detect libraries on OSX (which uses .dylib instead of .so). 
I tested it on my OSX machine. Let see if Travis likes it as well.
=> minor changes on wscripts to make it compatible with the .dylib format.

src/benchmarks/limbo/hp_opt.cpp, src/benchmarks/limbo/simple.cpp, waf_tools/limbo.py, waf_tools/mkl.py, waf_tools/tbb.py
(also include a patch for benchmarks... sorry)
=> improve support for OSX (detection of libraries)

wscript
=> Fix for #239

ci/install_libcmaes.sh, docs/tutorials/compilation.rst
=> Fix libcmaes Travis CI

docs/api.rst, src/limbo/mean/mean.hpp, src/tutorials/advanced_example.cpp
Update API docs for the BaseMean
=> Update API docs for the BaseMean

src/limbo/init/lhs.hpp, src/limbo/tools/random_generator.hpp, src/tests/test_init_functions.cpp
Adding LHS initialization..
@jbmouret @Aneoshun let me know if you find any obvious error..
=> Adding LHS initialization

src/limbo/opt/cmaes.hpp
Possibility of setting progress functions in CMA-ES
=> Possibility of setting progress functions in CMA-ES

src/limbo/opt.hpp, src/limbo/opt/adam.hpp, src/limbo/opt/gradient_ascent.hpp, src/tests/test_optimizers.cpp
This pull-request adds Adam and a few variants of (stochastic or not) gradient ascent (since we are maximing)..
@jbmouret @vassilisvas can you check it? I have optimized a few functions and the GP likelihood and they seem ok (sometimes they outperform Rprop, so they might be useful)..
=> Adding a few gradient-based optimizers

src/limbo/model/gp.hpp, src/limbo/model/multi_gp.hpp, src/limbo/serialize/binary_archive.hpp, src/limbo/serialize/text_archive.hpp
This PR adds save/load capabilities to `MultiGP` and a `mean_observation()` function that was missing..
=> MultiGP serialize

src/limbo/opt/optimizer.hpp, src/limbo/tools/math.hpp, src/limbo/tools/parallel.hpp, src/limbo/tools/random_generator.hpp
a few missing inline keywords (to avoid the export / multiple definition)
=> fix issue #276

src/limbo/model/gp.hpp, src/limbo/model/multi_gp.hpp
=> Fixes #278

src/limbo/model/multi_gp.hpp, src/limbo/serialize/binary_archive.hpp, src/limbo/serialize/text_archive.hpp, src/limbo/tools/random_generator.hpp, src/tests/test_serialize.cpp
This fixes #298 and a small bug in loading MultiGP. Adds also a regression test for this bug in `test_serialize`..
=> Fix for #298 and small bug in loading MultiGP

src/limbo/opt/nlopt_base.hpp, src/limbo/opt/nlopt_grad.hpp, src/limbo/opt/nlopt_no_grad.hpp, src/tests/test_nlopt.cpp, waf_tools/nlopt.py
This PR adds the possibility of adding constraints to our NLOpt wrapper. Also makes a small fix for detection of newer versions of NLOpt. This should fix #211 ...
=> NLOpt with constraints
